language: android
env:
    global:
        # Using the new Container-Based Infrastructure
        - sudo: false
        # Turning off caching to avoid caching Issues
        - cache: false
        # Initiating clean Gradle output
        - TERM=dumb
        # Giving even more memory to Gradle JVM
        - GRADLE_OPTS="-Xmx2048m -XX:MaxPermSize=1024m"
android:
    components:
        - build-tools-23.0.1
        - android-23
        - extra-android-m2repository
        - extra-google-m2repository
        - extra-android-support
    licenses:
        - android-sdk-license-5be876d5
script: ./gradlew clean check